eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost:23806/test?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 3
      auto-commit: true
      idle-timeout: 1000
      max-lifetime: 1800000
      connection-timeout: 30000
  profiles:
    active: dev
  application:
    name: member

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*Mapper.xml

logging:
  config: classpath:log4j2-spring.xml

server:
  port: 9092